spring.application.name=eureka-server
server.address=127.0.0.1
server.port=8761

spring.security.user.name=${EUREKA_USER:eureka}
spring.security.user.password=${EUREKA_PASSWORD:eureka}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@localhost:8761/eureka
eureka.instance.hostname=localhost

eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000