apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -w 3 mysql 3306 </dev/null; do echo waiting for mysql; sleep 3; done
      containers:
        - name: employee-service
          image: arjunchaudhary/employee-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: EUREKA_USER
              valueFrom:
                secretKeyRef:
                  name: eureka-secrets
                  key: EUREKA_USER
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eureka-secrets
                  key: EUREKA_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://$(EUREKA_USER):$(EUREKA_PASSWORD)@eureka-server:8761/eureka"

            - name: APP_DATASOURCE_EMPLOYEE_JDBC_URL
              value: "jdbc:mysql://mysql:3306/employee_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: APP_DATASOURCE_EMPLOYEE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EMPLOYEE_DB_USERNAME
            - name: APP_DATASOURCE_EMPLOYEE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EMPLOYEE_DB_PASSWORD
            - name: APP_DATASOURCE_ADDRESS_JDBC_URL
              value: "jdbc:mysql://mysql:3306/address_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: APP_DATASOURCE_ADDRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EMPLOYEE_ADDRESS_RO_USERNAME
            - name: APP_DATASOURCE_ADDRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EMPLOYEE_ADDRESS_RO_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: JWT_SECRET
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi