apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: microservices
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  EMPLOYEE_DB_USERNAME: employee_user
  EMPLOYEE_DB_PASSWORD: employee_pwd
  EMPLOYEE_ADDRESS_RO_USERNAME: employee_address_ro
  EMPLOYEE_ADDRESS_RO_PASSWORD: employee_ro_pwd
  ADDRESS_DB_USERNAME: address_user
  ADDRESS_DB_PASSWORD: address_pwd
  AUTH_DB_USERNAME: auth_user
  AUTH_DB_PASSWORD: auth_pwd
  JWT_SECRET: a3f1b8d4c9e2f706b8a9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f
---
apiVersion: v1
kind: Secret
metadata:
  name: eureka-secrets
  namespace: microservices
type: Opaque
stringData:
  EUREKA_USER: eureka
  EUREKA_PASSWORD: eureka